name: segundo_cogni
description: A starter project with splash screen, welcome flow, and Riverpod

environment:
  sdk: '^3.9.0'

dependencies:
  fluent_ui:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  flutter_svg:
  go_router:
  hooks_riverpod:
  http:
  sqflite_common_ffi: ^2.3.6
  syncfusion_flutter_datepicker: ^31.1.21
  path_provider:
  logger:
  flutter_dotenv:
  encrypt:
  crypto:

dependency_overrides:
  math_expressions: 3.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/logo.svg
