name: segundo_cogni
description: A starter project with splash screen, welcome flow, and Riverpod

environment:
  sdk: '^3.9.0'

dependencies:
  fluent_ui: ^4.0.0
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  flutter_svg:
  go_router:
  hooks_riverpod:
  http:
  sqflite_common_ffi: ^2.3.6
  syncfusion_flutter_datepicker: ^31.1.21
  path_provider:
  logger:
  flutter_dotenv:
  encrypt:
  crypto:
  cryptography: ^2.7.0
  bcrypt: ^1.1.3
  excel:
  record:

  # Option A: media_kit (cross-platform, recommended)
  media_kit:
  media_kit_video:
  media_kit_libs_windows_video:

  # Option B: video_player(+win) if you want it
  video_player:
  video_player_win:

dependency_overrides:
  math_expressions:

flutter:
  uses-material-design: true
  assets:
    - assets/video/task_prompts/
    - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
